spring.application.name=easystudy
spring.datasource.url=jdbc:mysql://localhost:3306/easystudy
spring.datasource.username=root
spring.datasource.password=rootroot

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true